### ISSUE TITLE
[BUG]: Cannot access 'check-pull-request-title' action in my Github Actions workflow

### ISSUE THREAD

**Issue by happyvig** [DylanVann/check-pull-request-title#1]
I tried using your action in my workflow in the same syntax as mentioned in the README. Getting the following error :

![image](https://user-images.githubusercontent.com/2972622/73515836-a074be80-441c-11ea-92bc-78ecc273becf.png)

Please help.

**Comment by rnitame** [comment]
This action is probably not public. Please publish! @DylanVann 
![image](https://user-images.githubusercontent.com/4950792/75505001-6ef01280-5a1d-11ea-813f-8cef7e832abc.png)

**Comment by rnitame** [comment]
Maybe referring to master instead of v1 might work @happyvig 

```yml
    steps:
      - uses: actions/checkout@v1
      - uses: dylanvann/check-pull-request-title@master <- change
```
